import { GoogleGenAI, Type } from '@google/genai';
import { SummaryLength, SummaryResponse } from '../types/summary';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const getWordLimit = (length: SummaryLength) => {
  switch (length) {
    case 'short':
      return '100-150 words';
    case 'medium':
      return '250-350 words';
    case 'long':
      return '500-700 words';
    default:
      return '250-350 words';
  }
};

export async function generateSummary(text: string, length: SummaryLength): Promise<SummaryResponse> {
  const wordLimit = getWordLimit(length);
  
  const systemInstruction = `You are an expert document summarization assistant. 
Your goal is to extract key insights, summarize the text accurately, and provide a structured analysis.
Strict rules:
1. Summarize ONLY information present in the text. DO NOT invent facts.
2. Preserve important numbers, names, dates, findings, and conclusions.
3. Your summary should be approximately ${wordLimit}.
4. Provide a few practical improvement suggestions based on the document's content (e.g. areas that are unclear).
5. Identify the main topics (up to 5 tags).
6. State the apparent document type (e.g., 'Research Paper', 'Invoice', 'Article').
7. DO NOT use generic filler phrases like 'Here is a comprehensive summary...' or 'Certainly!'. Make it sound like a professional productivity tool.
8. If the text appears incomplete, poorly formatted, or short, mention the uncertainty gracefully.`;

  const responseSchema = {
    type: Type.OBJECT,
    properties: {
      summary: {
        type: Type.STRING,
        description: `The main summary of the document, strictly adhering to the ${wordLimit} constraint.`,
      },
      keyPoints: {
        type: Type.ARRAY,
        items: { type: Type.STRING },
        description: 'A list of 3-6 important bullet points from the document.',
      },
      suggestions: {
        type: Type.ARRAY,
        items: { type: Type.STRING },
        description: 'Practical suggestions derived from the document (e.g., unclear sections, missing evidence). Leave empty if not applicable.',
      },
      documentType: {
        type: Type.STRING,
        description: 'The classified type of the document.',
      },
      importantTopics: {
        type: Type.ARRAY,
        items: { type: Type.STRING },
        description: 'Up to 5 topic tags/chips representing the content.',
      },
    },
    required: ['summary', 'keyPoints', 'suggestions', 'documentType', 'importantTopics'],
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: [{ role: 'user', parts: [{ text }] }],
    config: {
      systemInstruction: systemInstruction,
      responseMimeType: 'application/json',
      responseSchema: responseSchema,
      temperature: 0.2, // Low temperature for more factual summaries
    },
  });

  const responseText = response.text;
  if (!responseText) {
    throw new Error('No response generated by Gemini.');
  }

  try {
    return JSON.parse(responseText) as SummaryResponse;
  } catch (error) {
    console.error('Failed to parse Gemini response:', error);
    throw new Error('Invalid structured response from Gemini.');
  }
}
